### ISSUE TITLE
KeyError: 'BLOCKCHAIN_MONGO_DATA_DIR'

### ISSUE THREAD

**Issue by MalayTripathi** [asmiller1989/Ethereum_Blockchain_Parser#4]
Hi Alex, I am trying to run the stream.py script on an ubuntu 16.04 server with local geth node and MongoDB running. After installing pymongo and tqdm the script execution is stuck at this error. Please suggest me how to resolve it.

**Comment by N7Ren** [comment]
Hi,

you have to set an environment variable e.g. 
`export BLOCKCHAIN_MONGO_DATA_DIR=~/blockchain_data`

I think it doesn't matter to which directory it is set. In Analysis/analysis_util.py it is set to the current directory.

I'm running in jsonrpc errors now though but they are fixed with the open pull requests :)

**Comment by MalayTripathi** [comment]
Thanks rkernegger. I solved this. I worked great for me.
